### ISSUE TITLE
afl-gcc: not found

### ISSUE THREAD

**Issue by techstartupexplorer** [hardik05/Damn_Vulnerable_C_Program#3]
# make
AFL_HARDEN=1 afl-gcc   -fsanitize=address -fno-omit-frame-pointer -fsanitize=undefined imgRead.c -o imgRead 
/bin/sh: 1: afl-gcc: not found
make: *** [Makefile:12: all] Error 127

**Comment by hardik05** [comment]
you need to install afl or afl++ for this to work.
