### ISSUE TITLE
Compilation Error.

### ISSUE THREAD

**Issue by r00tb33** [hardik05/Damn_Vulnerable_C_Program#8]
I ran as stated in the README and in the video, stuck at the following error...

```
$ cargo build --release

....

   Compiling damn_vulnerable_c_program v0.1.0 (/home/xyz/fuzzing/LibAFL/fuzzers/Damn_Vulnerable_C_Program/libAFL/damn_vulnerable_c_program_git)
error: failed to run custom build command for `damn_vulnerable_c_program v0.1.0 (/home/xyz/fuzzing/LibAFL/fuzzers/Damn_Vulnerable_C_Program/libAFL/damn_vulnerable_c_program_git)`

Caused by:
  process didn't exit successfully: `/home/xyz/fuzzing/LibAFL/fuzzers/Damn_Vulnerable_C_Program/libAFL/damn_vulnerable_c_program_git/target/release/build/damn_vulnerable_c_program-2b86d6dad358ec2a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/main.rs

  --- stderr
  thread 'main' panicked at 'Couldn't clean program directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:19:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Awaiting for response!!

Thanks!!

**Comment by hardik05** [comment]
https://github.com/hardik05/Damn_Vulnerable_C_Program/blob/35a25bc1aa077c633b6150f60a9b7d92e3f9c7c4/libAFL/damn_vulnerable_c_program_git/build.rs#L19

Need to change dir here.

**Comment by r00tb33** [comment]
> https://github.com/hardik05/Damn_Vulnerable_C_Program/blob/35a25bc1aa077c633b6150f60a9b7d92e3f9c7c4/libAFL/damn_vulnerable_c_program_git/build.rs#L19
> 
> Need to change dir here.

To what exactly?

I am unable to figure out!!

**Comment by hardik05** [comment]
if you check the code, it looks for a dir inside release, just change it. this error is coming because that directory is not present on your system.

**Comment by r00tb33** [comment]
> if you check the code, it looks for a dir inside release, just change it. this error is coming because that directory is not present on your system.

Hi,

I've been through the code it looks for a binary in the (./target/release/) which is already present.

Talking about the directory it looks for it is "xpdf_dir" which is nothing but the current working directory which is valid.

I think the issue is something else.

**Comment by hardik05** [comment]
I just tried it on couple of vms at my sytem in hope to reproduce, but I am not able to replicate this issue.
